  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp2-html
  namespace: dev
spec:
  selector:
    matchLabels:
      app: bootcamp2-html
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bootcamp2-html
    spec:
      containers:
      - name: bootcamp2-html
        image: ramozer/bootcamp2:v$DOCKER_BUILD_NUMBER
        ports:
        - containerPort: 80
